[package]
edition = "2021"
name = "client"
version = "0.1.0"

[dependencies]
common = {path = "../common"}

anyhow = {workspace = true}
clap = {workspace = true}
thiserror = {workspace = true}
tokio = {workspace = true}
tracing = {workspace = true}
