[package]
edition = "2021"
name = "server"
version = "0.1.0"

[dependencies]
common = {path = "../common"}

anyhow = {workspace = true}
clap = {workspace = true}
thiserror = {workspace = true}
tracing = {workspace = true}
