volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_HOST: "0.0.0.0"
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
