volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_HOST: "0.0.0.0"
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
